name: Docker

on:
  workflow_dispatch:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: groupme-notify

jobs:
  test:
    runs-on: ubuntu-latest
    # dummy, tests maybe later
    steps:
      - uses: actions/checkout@v2
        
  publish:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: create binary directory
        run: mkdir -p fs

      - name: build notify
        run: GOOS=linux GOARCH=amd64 go build -o fs/notify ./main.go

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          repository: nhomble93/groupme-notify
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: nhomble/groupme-notify/groupme-notify
          tag_with_ref: true
